title: jekyll blog title - from feng hui
description: > # this means to ignore newlines until "baseurl:"
  jekyll blog description - from feng hui
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hui Feng # add your name
author-img: david-freeman.jpg # add your photo
about-author: Python and Django Engineer # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: feng-hui # add your Github handle
linkedin: # add your Linkedin handle
email: capricorn1203@126.com
weibo: capricorn1203

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 3
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
